# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

env:
  TASKFILE_MESSAGE: "Hello Taskfile"

dotenv: ['.env']

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  db_reset:
    cmds:
      - bundle exec rails db:drop
      - bundle exec rails db:prepare
      - task: psql_user_create
      - task: psql_user_password
      - task: psql_user_permissions

  guard:
    cmds:
      - bundle exec guard
    silent: true

  tailwind_build:
    cmds:
      - bundle exec rails tailwindcss:build

  tailwind_watch:
    cmds:
      - bundle exec rails tailwindcss:watch

  console:
    dotenv:
      - .bin/env
    cmds:
      - bundle exec rails console

  psql_user_create:
    cmds:
      - cmd:
         |
            psql -U $(whoami) postgres -c "
              create user spexops with password 'secret';
            "
        ignore_error: true

  psql_user_password:
    cmds:
      - |
        psql -U $(whoami) postgres -c "
          ALTER USER spexops PASSWORD 'secret';
        "
  setup:
    env:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
    cmds:
      - task: psql_user_create
      - bundle exec rails db:setup
      - task: psql_user_permissions
      - bundle exec rails db:migrate

  psql_user_permissions:
    cmds:
      - |
        setup () {
          echo "setting up database: ${2} for user: ${1}";
          psql -U $(whoami) ${2} -c "
            GRANT all privileges on DATABASE ${2} to ${1};
            GRANT ALL privileges on all TABLES in SCHEMA public to ${1};
            GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO ${1};
            GRANT ALL ON SCHEMA public TO ${1};
            GRANT USAGE ON SCHEMA public TO ${1};
            GRANT CONNECT ON DATABASE  ${2} to ${1};
            GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${1};
          "
        }
        setup "spexops" "spexops_cable_development"
        setup "spexops" "spexops_cache_development"
        setup "spexops" "spexops_queue_development"
        setup "spexops" "spexops_primary_development"
        setup "spexops" "spexops_accounts_development"
        setup "spexops" "spexops_projects_development"
        setup "spexops" "spexops_features_development"
        setup "spexops" "spexops_suites_development"
        setup "spexops" "spexops_specs_development"
        setup "spexops" "spexops_versions_development"