# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
default: &default
  adapter: solid_cable
  message_retention: 1.day
  connects_to:
    database:
      writing: cable

test:
  adapter: test

development:
  <<: *default
  polling_interval: 0.1.seconds

production:
  <<: *default
  polling_interval: 0.2.seconds
