default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
  <% end %>

development:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_PRIMARY_RW_URL'] %>
    database: primary_development
    migrations_paths: db/migrate_primary
  accounts:
    <<: *default
    url: <%= ENV['DATABASE_ACCOUNTS_RW_URL'] %>
    database: accounts_development
    migrations_paths: db/migrate_accounts
  projects:
    <<: *default
    url: <%= ENV['DATABASE_PROJECTS_RW_URL'] %>
    database: projects_development
    migrations_paths: db/migrate_projects
  features:
    <<: *default
    url: <%= ENV['DATABASE_FEATURES_RW_URL'] %>
    database: features_development
    migrations_paths: db/migrate_features
  suites:
    <<: *default
    url: <%= ENV['DATABASE_SUITES_RW_URL'] %>
    database: suites_development
    migrations_paths: db/migrate_suites
  specs:
    <<: *default
    url: <%= ENV['DATABASE_SPECS_RW_URL'] %>
    database: specs_development
    migrations_paths: db/migrate_specs
  versions:
    <<: *default
    url: <%= ENV['DATABASE_VERSIONS_RW_URL'] %>
    database: versions_development
    migrations_paths: db/migrate_versions

