default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
  <% end %>

development:
  cache:
    <<: *default
    url: <%= ENV['DATABASE_CACHE_RW_URL'] %>
    database: cache_development
    migrations_paths: db/migrate_cache
  cache_replica:
    <<: *default
    url: <%= ENV['DATABASE_CACHE_RO_URL'] %>
    database: cache_development
    replica: true
  queue:
    <<: *default
    url: <%= ENV['DATABASE_QUEUE_RW_URL'] %>
    database: queue_development
    migrations_paths: db/migrate_queue
  queue_replica:
    <<: *default
    url: <%= ENV['DATABASE_QUEUE_RO_URL'] %>
    database: queue_development
    replica: true
  primary:
    <<: *default
    url: <%= ENV['DATABASE_PRIMARY_RW_URL'] %>
    database: primary_development
    migrations_paths: db/migrate_primary
  primary_replica:
    <<: *default
    url: <%= ENV['DATABASE_PRIMARY_RO_URL'] %>
    database: primary_development
    replica: true
  accounts:
    <<: *default
    url: <%= ENV['DATABASE_ACCOUNTS_RW_URL'] %>
    database: accounts_development
    migrations_paths: db/migrate_accounts
  accounts_replica:
    <<: *default
    url: <%= ENV['DATABASE_ACCOUNTS_RO_URL'] %>
    database: accounts_development
    replica: true
  projects:
    <<: *default
    url: <%= ENV['DATABASE_PROJECTS_RW_URL'] %>
    database: projects_development
    migrations_paths: db/migrate_projects
  projects_replica:
    <<: *default
    url: <%= ENV['DATABASE_PROJECTS_RO_URL'] %>
    database: projects_development
    replica: true
  features:
    <<: *default
    url: <%= ENV['DATABASE_FEATURES_RW_URL'] %>
    database: features_development
    migrations_paths: db/migrate_features
  features_replica:
    <<: *default
    url: <%= ENV['DATABASE_FEATURES_RO_URL'] %>
    database: features_development
    replica: true
  suites:
    <<: *default
    url: <%= ENV['DATABASE_SUITES_RW_URL'] %>
    database: suites_development
    migrations_paths: db/migrate_suites
  suites_replica:
    <<: *default
    url: <%= ENV['DATABASE_SUITES_RO_URL'] %>
    database: suites_development
    replica: true
  specs:
    <<: *default
    url: <%= ENV['DATABASE_SPECS_RW_URL'] %>
    database: specs_development
    migrations_paths: db/migrate_specs
  specs_replica:
    <<: *default
    url: <%= ENV['DATABASE_SPECS_RO_URL'] %>
    database: specs_development
    replica: true
  versions:
    <<: *default
    url: <%= ENV['DATABASE_VERSIONS_RW_URL'] %>
    database: versions_development
    migrations_paths: db/migrate_versions
  versions_replica:
    <<: *default
    url: <%= ENV['DATABASE_VERSIONS_RO_URL'] %>
    database: versions_development
    replica: true

test:
  cache:
    <<: *default
    url: <%= ENV['DATABASE_CACHE_RW_URL'] %>
    database: cache_test
    migrations_paths: db/migrate_cache
  cache_replica:
    <<: *default
    url: <%= ENV['DATABASE_CACHE_RO_URL'] %>
    database: cache_development
    replica: true
  queue:
    <<: *default
    url: <%= ENV['DATABASE_QUEUE_RW_URL'] %>
    database: queue_test
    migrations_paths: db/migrate_queue
  queue_replica:
    <<: *default
    url: <%= ENV['DATABASE_QUEUE_RO_URL'] %>
    database: queue_test
    replica: true
  primary:
    <<: *default
    url: <%= ENV['DATABASE_PRIMARY_RW_URL'] %>
    database: primary_test
    migrations_paths: db/migrate_primary
  primary_replica:
    <<: *default
    url: <%= ENV['DATABASE_PRIMARY_RO_URL'] %>
    database: primary_test
    replica: true
  accounts:
    <<: *default
    url: <%= ENV['DATABASE_ACCOUNTS_RW_URL'] %>
    database: accounts_test
    migrations_paths: db/migrate_accounts
  accounts_replica:
    <<: *default
    url: <%= ENV['DATABASE_ACCOUNTS_RO_URL'] %>
    database: accounts_test
    replica: true
  projects:
    <<: *default
    url: <%= ENV['DATABASE_PROJECTS_RW_URL'] %>
    database: projects_test
    migrations_paths: db/migrate_projects
  projects_replica:
    <<: *default
    url: <%= ENV['DATABASE_PROJECTS_RO_URL'] %>
    database: projects_test
    replica: true
  features:
    <<: *default
    url: <%= ENV['DATABASE_FEATURES_RW_URL'] %>
    database: features_test
    migrations_paths: db/migrate_features
  features_replica:
    <<: *default
    url: <%= ENV['DATABASE_FEATURES_RO_URL'] %>
    database: features_test
    replica: true
  suites:
    <<: *default
    url: <%= ENV['DATABASE_SUITES_RW_URL'] %>
    database: suites_test
    migrations_paths: db/migrate_suites
  suites_replica:
    <<: *default
    url: <%= ENV['DATABASE_SUITES_RO_URL'] %>
    database: suites_test
    replica: true
  specs:
    <<: *default
    url: <%= ENV['DATABASE_SPECS_RW_URL'] %>
    database: specs_test
    migrations_paths: db/migrate_specs
  specs_replica:
    <<: *default
    url: <%= ENV['DATABASE_SPECS_RO_URL'] %>
    database: specs_test
    replica: true
  versions:
    <<: *default
    url: <%= ENV['DATABASE_VERSIONS_RW_URL'] %>
    database: versions_test
    migrations_paths: db/migrate_versions
  versions_replica:
    <<: *default
    url: <%= ENV['DATABASE_VERSIONS_RO_URL'] %>
    database: versions_test
    replica: true

production:
  cache:
    <<: *default
    url: <%= ENV['DATABASE_CACHE_RW_URL'] %>
    database: cache_production
    migrations_paths: db/migrate_cache
  cache_replica:
    <<: *default
    url: <%= ENV['DATABASE_CACHE_RO_URL'] %>
    database: cache_production
    replica: true
  queue:
    <<: *default
    url: <%= ENV['DATABASE_QUEUE_RW_URL'] %>
    database: queue_production
    migrations_paths: db/migrate_queue
  queue_replica:
    <<: *default
    url: <%= ENV['DATABASE_QUEUE_RO_URL'] %>
    database: queue_development
    replica: true
  primary:
    <<: *default
    url: <%= ENV['DATABASE_PRIMARY_RW_URL'] %>
    database: primary_production
    migrations_paths: db/migrate_primary
  primary_replica:
    <<: *default
    url: <%= ENV['DATABASE_PRIMARY_RO_URL'] %>
    database: primary_production
    replica: true
  accounts:
    <<: *default
    url: <%= ENV['DATABASE_ACCOUNTS_RW_URL'] %>
    database: accounts_production
    migrations_paths: db/migrate_accounts
  accounts_replica:
    <<: *default
    url: <%= ENV['DATABASE_ACCOUNTS_RO_URL'] %>
    database: accounts_production
    replica: true
  projects:
    <<: *default
    url: <%= ENV['DATABASE_PROJECTS_RW_URL'] %>
    database: projects_production
    migrations_paths: db/migrate_projects
  projects_replica:
    <<: *default
    url: <%= ENV['DATABASE_PROJECTS_RO_URL'] %>
    database: projects_production
    replica: true
  features:
    <<: *default
    url: <%= ENV['DATABASE_FEATURES_RW_URL'] %>
    database: features_production
    migrations_paths: db/migrate_features
  features_replica:
    <<: *default
    url: <%= ENV['DATABASE_FEATURES_RO_URL'] %>
    database: features_production
    replica: true
  suites:
    <<: *default
    url: <%= ENV['DATABASE_SUITES_RW_URL'] %>
    database: suites_production
    migrations_paths: db/migrate_suites
  suites_replica:
    <<: *default
    url: <%= ENV['DATABASE_SUITES_RO_URL'] %>
    database: suites_production
    replica: true
  specs:
    <<: *default
    url: <%= ENV['DATABASE_SPECS_RW_URL'] %>
    database: specs_production
    migrations_paths: db/migrate_specs
  specs_replica:
    <<: *default
    url: <%= ENV['DATABASE_SPECS_RO_URL'] %>
    database: specs_production
    replica: true
  versions:
    <<: *default
    url: <%= ENV['DATABASE_VERSIONS_RW_URL'] %>
    database: versions_production
    migrations_paths: db/migrate_versions
  versions_replica:
    <<: *default
    url: <%= ENV['DATABASE_VERSIONS_RO_URL'] %>
    database: versions_production
    replica: true
