FROM quay.io/keycloak/keycloak:26.0.7

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]

CMD ["start-dev", "--hostname=http://localhost:8080" , "--hostname-admin=http://localhost:8080" , "--http-enabled=true", "--verbose"]

